### ISSUE TITLE
PY2: TypeError: unbound method load_newobj() must be called with CompatUnpickler instance as first argument (got Unpickler instance instead)

### ISSUE THREAD

**Issue by Dncey** [Doist/pickle-compat#9]
Ubuntu 20.04, Python2.7
```
version: python2.7-pickle
         pickle-compat==2.1.0
```
```python2
import pickle
import pickle_compat
pickle_compat.unpatch()
s = ".........\x81......"
#   If there is this format('\x81') in the data, an error will be generated.   NEWOBJ = '\x81'
>>> pickle.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
TypeError: unbound method load_newobj() must be called with CompatUnpickler instance as first argument (got Unpickler instance instead)
```

**Comment by imankulov** [comment]
Hey @Dncey. Thanks for reporting the issue. There's a PR #11 that fixes the issue, but there's nobody to review it yet. If you're in a rush, you can pull the code directly from my branch: https://github.com/imankulov/pickle-compat/tree/roman/fix-type-error
